name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: "codebuild-async-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.os }}"
    strategy:
      matrix:
        os: [arm-3.0-medium, windows-3.0-small]
    steps:
      - run: echo "Hello World!"
