name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-async-${{ github.run_id }}-${{ github.run_attempt }}-linux-lambda-nodejs20-1GB
    steps:
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: 'true'
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
